resolved reload after logout and magic link message issues
tirthGajjar/designbits pull request #26
Opened 2022-04-07 11:23 UTC by Mihiirr

2022-04-07 11:35 UTC, tirthGajjar requested changes

2022-04-07 11:35 UTC, tirthGajjar commented on src/app/components/NavBar/ProfileDropdown.tsx
> +              </Form>
Move this into a separate component.

2022-04-07 11:35 UTC, tirthGajjar commented on src/app/components/NavBar/ProfileDropdown.tsx
> +                  className={classNames(
use clsx
```suggestion
                  className={clsx(
```

2022-04-08 03:44 UTC, Mihiirr commented on src/app/components/NavBar/ProfileDropdown.tsx
> +              </Form>
done

2022-04-08 03:44 UTC, Mihiirr commented on src/app/components/NavBar/ProfileDropdown.tsx
> +                  className={classNames(
done

2022-04-08 06:11 UTC, tirthGajjar approved these changes

2022-04-08 08:37 UTC, merged